sudo: required
services:
  - docker

before_install:
  - docker build -t pecardo/multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pecardo/multi npm test -- --coverage

after_success:
  - docker build -t pecardo/multi-client ./client
  - docker build -t pecardo/multi-nginx ./nginx
  - docker build -t pecardo/multi-server ./server
  - docker build -t pecardo/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push pecardo/multi-client
    - docker push pecardo/multi-nginx
    - docker push pecardo/multi-server
    - docker push pecardo/multi-worker

    