sudo: required
services:
  - docker

before_install:
  -docker build -t pecardo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pecardo/react-test npm test -- --coverage

after_success:
  - docker build -t pecardo/multi-client ./client
  - docker build -t pecardo/multi-nginx ./nginx
  - docker build -t pecardo/multi-server ./server
  - docker build -t pecardo/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
    - docker push pecardo/multi-client
    - docker push pecardo/multi-nginx
    - docker push pecardo/multi-server
    - docker push pecardo/multi-worker

    